# Use the official Flutter image as a parent image
FROM cirrusci/flutter:stable as build

# Set the working directory in the container
WORKDIR /app

# Copy the entire project to the container
COPY . .

# Get Flutter packages
RUN flutter pub get

# Build the app for the web
RUN flutter build web

# Use Nginx to serve the built app
FROM nginx:alpine

# Copy the built app to Nginx's serve directory
COPY --from=build /app/build/web /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]